# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "23:59"
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 50
  # Enable version updates for Github Action
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:59"
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 50
  # Enable version updates for docker-compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:59"
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 50